### ISSUE TITLE
Реализация алгоритма A* в нашем проекте.

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/PreCityMap#1]
# :question: Что это :question: 
Для поиска самого короткого пути нам понадобиться алгоритм `A*`.
> Поиск A* (произносится «А звезда» или «А стар», от англ. A star) — в информатике и математике, алгоритм поиска по первому наилучшему совпадению на графе, который находит маршрут с наименьшей стоимостью от одной вершины (начальной) к другой (целевой, конечной).

## Реализации в C++
  - ~~<http://code.activestate.com/recipes/577457-a-star-shortest-path-algorithm/>~~ :-1: 
  - <https://github.com/Sahnvour/PathFinder> :question: *Есть проблемы с компиляцией* 

# Задачи
  - [ ] Добавить алгоритм в наш репозиторий.
  - [ ] Сделать набросок A* для нашего проекта.
  - [ ] Использовать его в нашем проекте.

**Comment by mabramovsd** [comment]
[Задача о кратчайшем пути](https://ru.wikipedia.org/wiki/%D0%97%D0%B0%D0%B4%D0%B0%D1%87%D0%B0_%D0%BE_%D0%BA%D1%80%D0%B0%D1%82%D1%87%D0%B0%D0%B9%D1%88%D0%B5%D0%BC_%D0%BF%D1%83%D1%82%D0%B8) - это круто. Высшая математика и всё такое. Возможно, где-нибудь в марте (в сентябре точно никто суть алгоритма А*, Дейкстры или Флойда-Уоршелла не поймет) дойдем и до задач такого уровня, так что ссылку лучше сохранить. Если где-то в середине октября ты сможешь найти (не важно как - шантаж, запугивание, подкуп) единомышленников, которые захотят писать проект "карта города", эта штука сгодится.

**Comment by nm17** [comment]
> дойдем и до задач такого уровня

Я думаю что тем кто этим не интересуется не понять это.

**Comment by mabramovsd** [comment]
А всем понимать и не обязательно. Один человек функцию поиска кратчайшего пути пишет. Второй рисует кнопку "построить маршрут" и отвечает за чтение команд пользователя (первый клик мышки - пункт А, второй - пункт Б). Третий заполняет массив узловых точек (чтобы не по всем пикселям путь искать, а работать с графом меньшего размера) и отвечает за рисование сформированного кратчайшего маршрута на карте.

Так что если хочешь заниматься интересными задачами - это здорово! Просто надо найти пару человек, которые будут делать остальную работу и вместе вы сделаете крутой продукт

**Comment by nm17** [comment]
1. Как нам запихнуть целый виртуальный город в программу.
  2. Как добавить дороги как узлы для A*

**Comment by nm17** [comment]
На счёт первого: можно заполнить матрицу true и false. 

`return (txGetPixel(pos) == RGB(255,0,0))`

**Comment by nm17** [comment]
@mabramovsd можете помочь? Нужен какой-нибудь пример A*.

**Comment by mabramovsd** [comment]
Как нам запихнуть целый виртуальный город в программу. На счёт первого: можно заполнить матрицу true и false.
-Можно. Но этот случай плохо масштабируется (5000 зданий хранить в виде true и false - не круто). Лучше несколько более сложных массивов (допустим, каждое здание можно хранить как {левый верхний угол, ширина, высота}, дорогу как {координаты начала, координаты конца}, ну а узловые точки как {x, y}). В общем, если будете программировать карту города, я заставлю хранить карту в таком виде. Ну а для себя делай как тебе проще

можете помочь? Нужен какой-нибудь пример A*.
-google в помощь. Например, вот это нашел - http://gamesmaker.ru/files/68-volnovoy-algoritm-poiska-puti-na-c.txt . Если не найдешь А*, поищи другие алгоритмы из статьи с википедии (Дейкстры, Флойда-Уоршелла и т.д.). Тебя же не заставляют конкретный алгоритм юзать.
Ещё видео нашел https://www.youtube.com/watch?v=JFlSW3LQhFk (правда, скучное:))

**Comment by nm17** [comment]
@mabramovsd 

> [Например, вот это нашел](http://gamesmaker.ru/files/68-volnovoy-algoritm-poiska-puti-na-c.txt)

Проблема в том, что этот код очень некрасивый. Лучше использовать библиотеку [`Sahnvour/PathFinder`](https://github..com/Sahnvour/PathFinder), которая красивее.

### Пример из репы (перевод)
```cpp
#include <vector>
#include <iostream>
#include "PathFinder.h"
#include "AStar.h"

class MyNode : AStarNode
{
	/*
                Создаем чисто виртуальный метод из AStarNode.
	*/
};

int main()
{
	PathFinder<MyNode> myFinder; // Используется для поиска пути в графе MyNode
	
	std::vector<MyNode*> path;
	MyNode nodes[100];
	
	for(int i = 0; i < 100; ++i)
	{
		// Заполняйте вектор здесь, чтобы связать узлы между ними по мере необходимости
                // с помощью Node::addChild().
                // Это «настройка» вашего графика.
	}
	
	// Предположим что мы хотим, чтобы путь от первого узла до последнего...
	myFinder.setStart(nodes[0]);
	myFinder.setGoal(nodes[99]);

	// и все!
	bool result = myFinder.findPath<AStar>(path); // Просто укажите алгоритм, который вы хотите использовать.
	
	if(result)
		std::cout << "Success ! A path has been found." << std::endl;
	else
		std::cout << "Erk, it seems there is no way through." << std::endl;
	
	return 0;
}
```
