### ISSUE TITLE
Использование Google API для карты и вычисления пути.

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/PreCityMap#2]
В #1 я хотел использовать алгоритмы для вычесления пути.
Можно поступить по другому: использовать Google API

Например: `https://maps.googleapis.com/maps/api/directions/json?origin=Ulyanovsk&destination=Samara&key=` покажет расстояние от Ульяновска до Самары.

**Comment by mabramovsd** [comment]
А вот google maps не поможет. У нас города вымышленные будут
