### ISSUE TITLE
Исправление кода

### ISSUE THREAD

**Issue by mabramovsd** [IngenerkaTeamNewYork/PreCityMap#6]
Я удивен, но код выглядит неплохо)
Просьба исправить ещё несколько вещей:
  - [x] Главный файл называется Moohasransk City.cpp Что здесь может смутить? Нет, не это)) Чтобы не приходилось запускать файл с использованием кавычек, крайне желательно обходиться без пробелов. Так что переименуй, например, в MoohasranskCity.cpp
  - [x] Что за `cout << "> "`. Написал бы "введите код города"
  - [x] В 17 строке забыл точку с запятой
  - [x] Поправь форматирование. Много пустых строк, нет отступов

**Comment by nm17** [comment]
Исправлено в #7
